### ISSUE TITLE
Branch clean up 

### ISSUE THREAD

**Issue by AdrieanKhisbe** [johnbrett/calibrate#37]
Could you close all the spammed branches from `greenkeeper`? :smiley:

**Comment by johnbrett** [comment]
Cleaned up :) Yeah those get out of hand if you're not keeping a close eye!

**Comment by AdrieanKhisbe** [comment]
:clap:  ;)

**Comment by AdrieanKhisbe** [comment]
new branch come, do you know how to disable them?

**Comment by johnbrett** [comment]
It's done by greenkeeper. I'm hoping to try keep up with latest changes, leave it with me for a while to merge them when they come in. If it's too frequently, I'll disable it. It should be a simple case of just merging unless there is a major in any of the dependencies!

**Comment by AdrieanKhisbe** [comment]
I prefer relying on david(like) badge has warning.
Using `david` or `npm-check-upgrades` to then to update the package.json

I consider that for this Merge polutes history.

**Comment by johnbrett** [comment]
I usually do as well, but I just want to try out the greenkeeper workflow first :) It should be simply a case of merge & delete branch each time :)

**Comment by AdrieanKhisbe** [comment]
No problem :)
(has long as you fast forward merge :p)
