### ISSUE TITLE
Glue integration

### ISSUE THREAD

**Issue by AVVS** [johnbrett/calibrate#55]
https://www.npmjs.com/package/glue only accepts strings to be required as a plugin module, so could you move decorate to module.exports and default to some prop?

**Comment by johnbrett** [comment]
Hey @AVVS, great spot on this, looking into it now. Sorry for delay.

**Comment by johnbrett** [comment]
Hey @AVVS. I've pushed a new version now, you should be able to add calibrate to your manifest via the string:

`calibrate/decorate`

now. Let me know if you have any issues.
