### ISSUE TITLE
Update to v17

### ISSUE THREAD

**Issue by tinchoz49** [johnbrett/calibrate#82]
Hi @johnbrett, how are you?

First, I want to say that this is a really good plugin for hapi, thanks for your work.

Are you planning to update it to hapi v17?

**Comment by johnbrett** [comment]
Hi @tinchoz49, thanks for the feedback on the project - really appreciated.

Thanks to fantastic work by @estebanprimost, v4 of this plugin now supports hapi v17: https://github.com/johnbrett/calibrate/pull/83.

**Comment by tinchoz49** [comment]
thanks @johnbrett @estebanprimost! :+1:
