### ISSUE TITLE
Question: Why doesn't the hapi decorator support the "meta" parameter?

### ISSUE THREAD

**Issue by nickrobillard** [johnbrett/calibrate#88]
I am curious why the hapi decorator does not allow for the 2nd parameter "meta" object.

I can do this in a hapi route handler:

`return Calibrate(data, meta);`

But I can't do this ("meta" has no effect):

`return h.calibrate(data, meta);`

Because of this calibrate code:

```
const calibrateDeocorator = function (data) {
  return internals.calibrate(data);
};
server.decorate('toolkit', 'calibrate', calibrateDeocorator);
```

**Comment by nickrobillard** [comment]
Oh I see now that #71 was an attempt to do this. But it appears to have not made it into index.js. Can we try this again? :)

**Comment by johnbrett** [comment]
Hi Nick,

I'm open to working with you on trying to make this happen if you can
submit a PR?

**Comment by johnbrett** [comment]
Resolved via https://github.com/johnbrett/calibrate/pull/89
